# Generated by Django 2.1 on 2018-09-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echouser',
            options={'ordering': ['user_id', '-points']},
        ),
    ]
