# Generated by Django 2.0.8 on 2018-10-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='echousersubmission',
            name='pid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='echousersubmission',
            name='submission_text',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='pid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
