# Generated by Django 2.0.8 on 2018-10-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181030_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='echouser',
            options={'ordering': ['user_id', '-rank']},
        ),
        migrations.RemoveField(
            model_name='echouser',
            name='points',
        ),
        migrations.AddField(
            model_name='echouser',
            name='pid',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='echousersubmission',
            name='files',
            field=models.FileField(upload_to='media/'),
        ),
    ]
